# Generated by Django 6.0 on 2026-08-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expensecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
