/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminExpensesRouteImport } from './routes/admin.expenses'
import { Route as AdminInvestmentsRouteImport } from './routes/admin.investments'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as UserExpensesRouteImport } from './routes/user.expenses'
import { Route as UserInvestmentsRouteImport } from './routes/user.investments'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/admin/expenses',
  path: '/admin/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvestmentsRoute = AdminInvestmentsRouteImport.update({
  id: '/admin/investments',
  path: '/admin/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UserExpensesRoute = UserExpensesRouteImport.update({
  id: '/user/expenses',
  path: '/user/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const UserInvestmentsRoute = UserInvestmentsRouteImport.update({
  id: '/user/investments',
  path: '/user/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/expenses': typeof UserExpensesRoute
  '/user/investments': typeof UserInvestmentsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/expenses': typeof UserExpensesRoute
  '/user/investments': typeof UserInvestmentsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/expenses': typeof UserExpensesRoute
  '/user/investments': typeof UserInvestmentsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/expenses'
    | '/admin/investments'
    | '/user/dashboard'
    | '/user/expenses'
    | '/user/investments'
    | '/admin/users/$userId'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/expenses'
    | '/admin/investments'
    | '/user/dashboard'
    | '/user/expenses'
    | '/user/investments'
    | '/admin/users/$userId'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/expenses'
    | '/admin/investments'
    | '/user/dashboard'
    | '/user/expenses'
    | '/user/investments'
    | '/admin/users/$userId'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExpensesRoute: typeof AdminExpensesRoute
  AdminInvestmentsRoute: typeof AdminInvestmentsRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserExpensesRoute: typeof UserExpensesRoute
  UserInvestmentsRoute: typeof UserInvestmentsRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/investments': {
      id: '/admin/investments'
      path: '/admin/investments'
      fullPath: '/admin/investments'
      preLoaderRoute: typeof AdminInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/expenses': {
      id: '/user/expenses'
      path: '/user/expenses'
      fullPath: '/user/expenses'
      preLoaderRoute: typeof UserExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/investments': {
      id: '/user/investments'
      path: '/user/investments'
      fullPath: '/user/investments'
      preLoaderRoute: typeof UserInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminInvestmentsRoute: AdminInvestmentsRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserExpensesRoute: UserExpensesRoute,
  UserInvestmentsRoute: UserInvestmentsRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
